// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SabconIot

#ifndef _SABCONIOT_UI_H
#define _SABCONIOT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScrLogin
void ui_ScrLogin_screen_init(void);
extern lv_obj_t *ui_ScrLogin;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Container2;
void ui_event_Panel8( lv_event_t * e);
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label8;
void ui_event_Panel9( lv_event_t * e);
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label5;
void ui_event_Panel10( lv_event_t * e);
extern lv_obj_t *ui_Panel10;
void ui_event_Image3( lv_event_t * e);
extern lv_obj_t *ui_Image3;
void ui_event_BtnBackLogin( lv_event_t * e);
extern lv_obj_t *ui_BtnBackLogin;
extern lv_obj_t *ui_Label58;
// CUSTOM VARIABLES

// SCREEN: ui_ScrMain
void ui_ScrMain_screen_init(void);
extern lv_obj_t *ui_ScrMain;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_LblStationName;
extern lv_obj_t *ui_Container15;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_LblOperatorName;
void ui_event_Container7( lv_event_t * e);
extern lv_obj_t *ui_Container7;
void ui_event_Image2( lv_event_t * e);
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Body;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPage1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_PnlOpDisplay;
extern lv_obj_t *ui_TabPage2;
extern lv_obj_t *ui_PnlOpDisplay3;
extern lv_obj_t *ui_Container17;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_dataDefaultTimeLabel;
extern lv_obj_t *ui_dataDefaultTime;
extern lv_obj_t *ui_dataDefaultTimeUnit;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_dataAvarageTimeLabel;
extern lv_obj_t *ui_dataAvarageTime;
extern lv_obj_t *ui_dataAvarageTimeUnit;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_dataPiecesCountLabel;
extern lv_obj_t *ui_dataPiecesCount;
extern lv_obj_t *ui_dataPiecesCountUnit;
extern lv_obj_t *ui_Container40;
extern lv_obj_t *ui_dataPiecesRejectedLabel;
extern lv_obj_t *ui_dataPiecesRejected;
extern lv_obj_t *ui_dataPiecesRejectedUnit;
extern lv_obj_t *ui_TabPage3;
extern lv_obj_t *ui_Footer;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ScrPassword
void ui_ScrPassword_screen_init(void);
extern lv_obj_t *ui_ScrPassword;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_LblOperatorNameLogin;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_TxtPin;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_LblUserID;
// CUSTOM VARIABLES

// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
extern lv_obj_t *ui_ScrSettings;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_LblDeviceID;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_LblCompanyName;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_LblWifiSSID;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Lbl;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label56;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_580822032);   // assets/cogwheel-setting-small.png
LV_IMG_DECLARE( ui_img_user_change_png);   // assets/user_change.png
LV_IMG_DECLARE( ui_img_right_png);   // assets/right.png
LV_IMG_DECLARE( ui_img_1212854978);   // assets/play (2).png
LV_IMG_DECLARE( ui_img_pause_png);   // assets/pause.png

// FONTS
LV_FONT_DECLARE( ui_font_Barlow16);
LV_FONT_DECLARE( ui_font_BarlowBold16);
LV_FONT_DECLARE( ui_font_BarlowBold20);
LV_FONT_DECLARE( ui_font_BarlowBold24);
LV_FONT_DECLARE( ui_font_Barlow18);
LV_FONT_DECLARE( ui_font_Barlow24);
LV_FONT_DECLARE( ui_font_Barlow22);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
