// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SabconIot

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void StartOperation(lv_event_t * e);
void CmdRunningOpStart(lv_event_t * e);
void CmdRunningOpPause(lv_event_t * e);
void CheckPassword(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
