// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SabconIot

#include "../ui.h"

void ui_event_comp_PnlOpDisplay_PnlOpDisplay( lv_event_t * e) {
  lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_PnlOpDisplay = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
    OpenOperationScreen( e );
}
}
// COMPONENT PnlOpDisplay

lv_obj_t *ui_PnlOpDisplay_create(lv_obj_t *comp_parent, const char *op_number, const char *product_name, const char *amount, const char *date) {

lv_obj_t *cui_PnlOpDisplay;
cui_PnlOpDisplay = lv_obj_create(comp_parent);
lv_obj_set_height( cui_PnlOpDisplay, 120);
lv_obj_set_width( cui_PnlOpDisplay, lv_pct(100));
lv_obj_set_flex_flow(cui_PnlOpDisplay,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(cui_PnlOpDisplay, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( cui_PnlOpDisplay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(cui_PnlOpDisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_PnlOpDisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_PnlOpDisplay, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_PnlOpDisplay, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_PnlOpDisplay, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_PnlOpDisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_PnlOpDisplay, lv_color_hex(0x6CFF8C), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(cui_PnlOpDisplay, 100, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_bg_color(cui_PnlOpDisplay, lv_color_hex(0xF0FF6C), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_opa(cui_PnlOpDisplay, 100, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_bg_color(cui_PnlOpDisplay, lv_color_hex(0xFF6C6C), LV_PART_MAIN | LV_STATE_USER_3 );
lv_obj_set_style_bg_opa(cui_PnlOpDisplay, 100, LV_PART_MAIN| LV_STATE_USER_3);

lv_obj_t *cui_Container19;
cui_Container19 = lv_obj_create(cui_PnlOpDisplay);
lv_obj_remove_style_all(cui_Container19);
lv_obj_set_height( cui_Container19, 20);
lv_obj_set_width( cui_Container19, lv_pct(100));
lv_obj_set_align( cui_Container19, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container19,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Container19, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Container19, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label7;
cui_Label7 = lv_label_create(cui_Container19);
lv_obj_set_width( cui_Label7, 100);
lv_obj_set_height( cui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label7,"OP:");
lv_obj_set_style_text_align(cui_Label7, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label7, &ui_font_BarlowBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LblOpNumber;
cui_LblOpNumber = lv_label_create(cui_Container19);
lv_obj_set_width( cui_LblOpNumber, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LblOpNumber, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LblOpNumber, LV_ALIGN_CENTER );
lv_label_set_text(cui_LblOpNumber, op_number);
lv_obj_set_style_text_font(cui_LblOpNumber, &ui_font_Barlow16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container20;
cui_Container20 = lv_obj_create(cui_PnlOpDisplay);
lv_obj_remove_style_all(cui_Container20);
lv_obj_set_height( cui_Container20, 20);
lv_obj_set_width( cui_Container20, lv_pct(100));
lv_obj_set_align( cui_Container20, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container20,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Container20, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Container20, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label17;
cui_Label17 = lv_label_create(cui_Container20);
lv_obj_set_width( cui_Label17, 100);
lv_obj_set_height( cui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label17,"Produto:");
lv_obj_set_style_text_align(cui_Label17, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label17, &ui_font_BarlowBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LblOpOProduct;
cui_LblOpOProduct = lv_label_create(cui_Container20);
lv_obj_set_width( cui_LblOpOProduct, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LblOpOProduct, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LblOpOProduct, LV_ALIGN_CENTER );
lv_label_set_text(cui_LblOpOProduct, product_name);
lv_obj_set_style_text_font(cui_LblOpOProduct, &ui_font_Barlow16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container21;
cui_Container21 = lv_obj_create(cui_PnlOpDisplay);
lv_obj_remove_style_all(cui_Container21);
lv_obj_set_height( cui_Container21, 20);
lv_obj_set_width( cui_Container21, lv_pct(100));
lv_obj_set_align( cui_Container21, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container21,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container21, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Container21, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Container21, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label20;
cui_Label20 = lv_label_create(cui_Container21);
lv_obj_set_width( cui_Label20, 100);
lv_obj_set_height( cui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label20,"Quantidade:");
lv_obj_set_style_text_align(cui_Label20, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label20, &ui_font_BarlowBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LblOpAmount;
cui_LblOpAmount = lv_label_create(cui_Container21);
lv_obj_set_width( cui_LblOpAmount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LblOpAmount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LblOpAmount, LV_ALIGN_CENTER );
lv_label_set_text(cui_LblOpAmount, amount);
lv_obj_set_style_text_font(cui_LblOpAmount, &ui_font_Barlow16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container22;
cui_Container22 = lv_obj_create(cui_PnlOpDisplay);
lv_obj_remove_style_all(cui_Container22);
lv_obj_set_height( cui_Container22, 20);
lv_obj_set_width( cui_Container22, lv_pct(100));
lv_obj_set_align( cui_Container22, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container22,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( cui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Container22, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Container22, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label22;
cui_Label22 = lv_label_create(cui_Container22);
lv_obj_set_width( cui_Label22, 100);
lv_obj_set_height( cui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label22,"Data Início:");
lv_obj_set_style_text_align(cui_Label22, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label22, &ui_font_BarlowBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LblOpStartDate;
cui_LblOpStartDate = lv_label_create(cui_Container22);
lv_obj_set_width( cui_LblOpStartDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LblOpStartDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_LblOpStartDate, LV_ALIGN_CENTER );
lv_label_set_text(cui_LblOpStartDate, date);
lv_obj_set_style_text_font(cui_LblOpStartDate, &ui_font_Barlow16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PNLOPDISPLAY_NUM);
children[UI_COMP_PNLOPDISPLAY_PNLOPDISPLAY] = cui_PnlOpDisplay;
children[UI_COMP_PNLOPDISPLAY_CONTAINER19] = cui_Container19;
children[UI_COMP_PNLOPDISPLAY_CONTAINER19_LABEL7] = cui_Label7;
children[UI_COMP_PNLOPDISPLAY_CONTAINER19_LBLOPNUMBER] = cui_LblOpNumber;
children[UI_COMP_PNLOPDISPLAY_CONTAINER20] = cui_Container20;
children[UI_COMP_PNLOPDISPLAY_CONTAINER20_LABEL17] = cui_Label17;
children[UI_COMP_PNLOPDISPLAY_CONTAINER20_LBLOPOPRODUCT] = cui_LblOpOProduct;
children[UI_COMP_PNLOPDISPLAY_CONTAINER21] = cui_Container21;
children[UI_COMP_PNLOPDISPLAY_CONTAINER21_LABEL20] = cui_Label20;
children[UI_COMP_PNLOPDISPLAY_CONTAINER21_LBLOPAMOUNT] = cui_LblOpAmount;
children[UI_COMP_PNLOPDISPLAY_CONTAINER22] = cui_Container22;
children[UI_COMP_PNLOPDISPLAY_CONTAINER22_LABEL22] = cui_Label22;
children[UI_COMP_PNLOPDISPLAY_CONTAINER22_LBLOPSTARTDATE] = cui_LblOpStartDate;
lv_obj_add_event_cb(cui_PnlOpDisplay, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_PnlOpDisplay, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_PnlOpDisplay_create_hook(cui_PnlOpDisplay);
return cui_PnlOpDisplay; 
}

