// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SabconIot

#ifndef _UI_COMP_PNLOPDISPLAY_H
#define _UI_COMP_PNLOPDISPLAY_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PnlOpDisplay
#define UI_COMP_PNLOPDISPLAY_PNLOPDISPLAY 0
#define UI_COMP_PNLOPDISPLAY_CONTAINER19 1
#define UI_COMP_PNLOPDISPLAY_CONTAINER19_LABEL7 2
#define UI_COMP_PNLOPDISPLAY_CONTAINER19_LBLOPNUMBER 3
#define UI_COMP_PNLOPDISPLAY_CONTAINER20 4
#define UI_COMP_PNLOPDISPLAY_CONTAINER20_LABEL17 5
#define UI_COMP_PNLOPDISPLAY_CONTAINER20_LBLOPOPRODUCT 6
#define UI_COMP_PNLOPDISPLAY_CONTAINER21 7
#define UI_COMP_PNLOPDISPLAY_CONTAINER21_LABEL20 8
#define UI_COMP_PNLOPDISPLAY_CONTAINER21_LBLOPAMOUNT 9
#define UI_COMP_PNLOPDISPLAY_CONTAINER22 10
#define UI_COMP_PNLOPDISPLAY_CONTAINER22_LABEL22 11
#define UI_COMP_PNLOPDISPLAY_CONTAINER22_LBLOPSTARTDATE 12
#define _UI_COMP_PNLOPDISPLAY_NUM 13
lv_obj_t *ui_PnlOpDisplay_create(lv_obj_t *comp_parent, const char *op_number, const char *product_name, const char *amount, const char *date);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
