// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SabconIot

#include "../ui.h"

void ui_ScrPassword_screen_init(void)
{
ui_ScrPassword = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScrPassword, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScrPassword,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ScrPassword, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_ScrPassword, lv_color_hex(0x592D90), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScrPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_ScrPassword);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_height( ui_Container4, lv_pct(12));
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Login Operador:");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblOperatorNameLogin = lv_label_create(ui_Container4);
lv_obj_set_width( ui_LblOperatorNameLogin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblOperatorNameLogin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblOperatorNameLogin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblOperatorNameLogin,"Julio Brim");
lv_obj_set_style_text_color(ui_LblOperatorNameLogin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblOperatorNameLogin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblOperatorNameLogin, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_ScrPassword);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, lv_pct(80));
lv_obj_set_height( ui_Container5, lv_pct(20));
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container5, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"PIN: ");
lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label16, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TxtPin = lv_textarea_create(ui_Container5);
lv_obj_set_width( ui_TxtPin, 100);
lv_obj_set_height( ui_TxtPin, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_TxtPin, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_TxtPin,6);
lv_textarea_set_one_line(ui_TxtPin,true);
lv_textarea_set_password_mode(ui_TxtPin, true);
lv_obj_remove_flag( ui_TxtPin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_align(ui_TxtPin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TxtPin, &ui_font_BarlowBold20, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Keyboard1 = lv_keyboard_create(ui_ScrPassword);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 400);
lv_obj_set_height( ui_Keyboard1, 220);
lv_obj_set_x( ui_Keyboard1, -147 );
lv_obj_set_y( ui_Keyboard1, 58 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_LblUserID = lv_label_create(ui_ScrPassword);
lv_obj_set_width( ui_LblUserID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblUserID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblUserID, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblUserID,"");

lv_keyboard_set_textarea(ui_Keyboard1,ui_TxtPin);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}
