// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SabconIot

#include "../ui.h"

void ui_ScrMain_screen_init(void)
{
ui_ScrMain = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScrMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScrMain,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ScrMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Header = lv_obj_create(ui_ScrMain);
lv_obj_remove_style_all(ui_Header);
lv_obj_set_width( ui_Header, lv_pct(100));
lv_obj_set_height( ui_Header, lv_pct(15));
lv_obj_set_align( ui_Header, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Header,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Header, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x5D139C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Header, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Header, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Header, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Header, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, lv_pct(80));
lv_obj_set_height( ui_Container8, lv_pct(100));
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container14 = lv_obj_create(ui_Container8);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_height( ui_Container14, 50);
lv_obj_set_width( ui_Container14, lv_pct(100));
lv_obj_set_align( ui_Container14, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container14,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container14, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Container14);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label3,"Estação:");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblStationName = lv_label_create(ui_Container14);
lv_obj_set_width( ui_LblStationName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblStationName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LblStationName, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LblStationName,"Costura 01");
lv_obj_set_style_text_color(ui_LblStationName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblStationName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblStationName, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container15 = lv_obj_create(ui_Container8);
lv_obj_remove_style_all(ui_Container15);
lv_obj_set_height( ui_Container15, 50);
lv_obj_set_width( ui_Container15, lv_pct(100));
lv_obj_set_align( ui_Container15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container15,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container15, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Container15);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label13,"Operador:");
lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LblOperatorName = lv_label_create(ui_Container15);
lv_obj_set_width( ui_LblOperatorName, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_LblOperatorName, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_LblOperatorName, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LblOperatorName,"Julio Cesar Brim Brim");
lv_obj_set_style_text_color(ui_LblOperatorName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblOperatorName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblOperatorName, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, lv_pct(20));
lv_obj_set_height( ui_Container7, lv_pct(100));
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_image_create(ui_Container7);
lv_image_set_src(ui_Image2, &ui_img_user_change_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image2,100);

ui_Body = lv_obj_create(ui_ScrMain);
lv_obj_remove_style_all(ui_Body);
lv_obj_set_width( ui_Body, lv_pct(100));
lv_obj_set_flex_grow( ui_Body, 1);
lv_obj_set_align( ui_Body, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Body, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Body, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Body, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Body, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView1 = lv_tabview_create(ui_Body);
lv_tabview_set_tab_bar_position(ui_TabView1,LV_DIR_BOTTOM);
lv_tabview_set_tab_bar_size(ui_TabView1,50);
lv_obj_set_width( ui_TabView1, lv_pct(100));
lv_obj_set_height( ui_TabView1, lv_pct(100));
lv_obj_remove_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView1), &ui_font_BarlowBold20,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x5D139C),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Ordens");

ui_Container1 = lv_obj_create(ui_TabPage1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_height( ui_Container1, 550);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Container1, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_Container1, LV_DIR_VER);
lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xCA2A2A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Container1);
lv_obj_set_height( ui_Panel7, 50);
lv_obj_set_width( ui_Panel7, lv_pct(100));
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Panel7, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Sem ordens de produção");
lv_obj_set_style_text_font(ui_Label6, &ui_font_BarlowBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Em Execução");
lv_obj_set_flex_flow(ui_TabPage2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_TabPage2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_PnlOpDisplay3 = ui_PnlOpDisplay_create(ui_TabPage2, "OP 0003", "Sofá Retrátil", "15 pçs", "01/01/2022");
lv_obj_set_x( ui_PnlOpDisplay3, 0 );
lv_obj_set_y( ui_PnlOpDisplay3, 0 );

ui_Container17 = lv_obj_create(ui_TabPage2);
lv_obj_remove_style_all(ui_Container17);
lv_obj_set_height( ui_Container17, 75);
lv_obj_set_width( ui_Container17, lv_pct(100));
lv_obj_set_align( ui_Container17, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container17,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container17, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container17, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_image_create(ui_Container17);
lv_image_set_src(ui_Image5, &ui_img_1212854978);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Image5, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Image5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_image_create(ui_Container17);
lv_image_set_src(ui_Image4, &ui_img_pause_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_TabPage2);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, lv_pct(100));
lv_obj_set_height( ui_Container6, lv_pct(49));
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_height( ui_Container2, 30);
lv_obj_set_width( ui_Container2, lv_pct(100));
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataDefaultTimeLabel = lv_label_create(ui_Container2);
lv_obj_set_width( ui_dataDefaultTimeLabel, lv_pct(60));
lv_obj_set_height( ui_dataDefaultTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataDefaultTimeLabel,"Velocidade Planejada:");
lv_obj_set_style_text_align(ui_dataDefaultTimeLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataDefaultTimeLabel, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataDefaultTime = lv_label_create(ui_Container2);
lv_obj_set_width( ui_dataDefaultTime, lv_pct(25));
lv_obj_set_height( ui_dataDefaultTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dataDefaultTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_dataDefaultTime,"30");
lv_obj_set_style_text_align(ui_dataDefaultTime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataDefaultTime, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataDefaultTimeUnit = lv_label_create(ui_Container2);
lv_obj_set_width( ui_dataDefaultTimeUnit, lv_pct(15));
lv_obj_set_height( ui_dataDefaultTimeUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dataDefaultTimeUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_dataDefaultTimeUnit,"ppm");
lv_obj_set_style_text_font(ui_dataDefaultTimeUnit, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_dataDefaultTimeUnit, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_dataDefaultTimeUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_dataDefaultTimeUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_dataDefaultTimeUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_height( ui_Container3, 30);
lv_obj_set_width( ui_Container3, lv_pct(100));
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataAvarageTimeLabel = lv_label_create(ui_Container3);
lv_obj_set_width( ui_dataAvarageTimeLabel, lv_pct(60));
lv_obj_set_height( ui_dataAvarageTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataAvarageTimeLabel,"Velocidade atual:");
lv_obj_set_style_text_align(ui_dataAvarageTimeLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataAvarageTimeLabel, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataAvarageTime = lv_label_create(ui_Container3);
lv_obj_set_width( ui_dataAvarageTime, lv_pct(25));
lv_obj_set_height( ui_dataAvarageTime, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataAvarageTime,"28");
lv_obj_set_style_text_align(ui_dataAvarageTime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataAvarageTime, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataAvarageTimeUnit = lv_label_create(ui_Container3);
lv_obj_set_width( ui_dataAvarageTimeUnit, lv_pct(15));
lv_obj_set_height( ui_dataAvarageTimeUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dataAvarageTimeUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_dataAvarageTimeUnit,"ppm");
lv_obj_set_style_text_font(ui_dataAvarageTimeUnit, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_dataAvarageTimeUnit, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_dataAvarageTimeUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_dataAvarageTimeUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_dataAvarageTimeUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_height( ui_Container4, 30);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container4, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataPiecesCountLabel = lv_label_create(ui_Container4);
lv_obj_set_width( ui_dataPiecesCountLabel, lv_pct(60));
lv_obj_set_height( ui_dataPiecesCountLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataPiecesCountLabel,"Peças produzidas:");
lv_obj_set_style_text_align(ui_dataPiecesCountLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataPiecesCountLabel, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataPiecesCount = lv_label_create(ui_Container4);
lv_obj_set_width( ui_dataPiecesCount, lv_pct(25));
lv_obj_set_height( ui_dataPiecesCount, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataPiecesCount,"203");
lv_obj_set_style_text_align(ui_dataPiecesCount, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataPiecesCount, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataPiecesCountUnit = lv_label_create(ui_Container4);
lv_obj_set_width( ui_dataPiecesCountUnit, lv_pct(15));
lv_obj_set_height( ui_dataPiecesCountUnit, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataPiecesCountUnit,"pçs");
lv_obj_set_style_text_font(ui_dataPiecesCountUnit, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_dataPiecesCountUnit, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_dataPiecesCountUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_dataPiecesCountUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_dataPiecesCountUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container40 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container40);
lv_obj_set_height( ui_Container40, 30);
lv_obj_set_width( ui_Container40, lv_pct(100));
lv_obj_set_align( ui_Container40, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container40,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container40, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container40, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container40, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container40, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container40, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container40, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataPiecesRejectedLabel = lv_label_create(ui_Container40);
lv_obj_set_width( ui_dataPiecesRejectedLabel, lv_pct(60));
lv_obj_set_height( ui_dataPiecesRejectedLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataPiecesRejectedLabel,"Peças rejeitadas:");
lv_obj_set_style_text_align(ui_dataPiecesRejectedLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataPiecesRejectedLabel, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataPiecesRejected = lv_label_create(ui_Container40);
lv_obj_set_width( ui_dataPiecesRejected, lv_pct(25));
lv_obj_set_height( ui_dataPiecesRejected, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataPiecesRejected,"10");
lv_obj_set_style_text_align(ui_dataPiecesRejected, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dataPiecesRejected, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dataPiecesRejectedUnit = lv_label_create(ui_Container40);
lv_obj_set_width( ui_dataPiecesRejectedUnit, lv_pct(15));
lv_obj_set_height( ui_dataPiecesRejectedUnit, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_dataPiecesRejectedUnit,"pçs");
lv_obj_set_style_text_font(ui_dataPiecesRejectedUnit, &ui_font_Barlow22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_dataPiecesRejectedUnit, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_dataPiecesRejectedUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_dataPiecesRejectedUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_dataPiecesRejectedUnit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Manejo");

ui_Footer = lv_obj_create(ui_ScrMain);
lv_obj_remove_style_all(ui_Footer);
lv_obj_set_width( ui_Footer, lv_pct(100));
lv_obj_set_height( ui_Footer, lv_pct(6));
lv_obj_set_align( ui_Footer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Footer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Footer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Footer, lv_color_hex(0x5D139C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Footer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container9 = lv_obj_create(ui_Footer);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 100);
lv_obj_set_height( ui_Container9, 50);
lv_obj_set_align( ui_Container9, LV_ALIGN_RIGHT_MID );
lv_obj_remove_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Container9);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_BarlowBold24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Container7, ui_event_Container7, LV_EVENT_ALL, NULL);

}
